### ISSUE TITLE
出现不支持的音频/视频 或设备无网络问题

### ISSUE THREAD

**Issue by wcpcp** [sctm002/video_down#1]
这个要怎么解决呢
![20567455a860bb3739a8475bf39894f](https://github.com/user-attachments/assets/75e3d70a-d80d-44f4-bf75-20c1e4e2b97a)

**Comment by wcpcp** [comment]
![image](https://github.com/user-attachments/assets/51a60a3e-de88-4993-9cef-a7e5e99f2d98)
补充终端信息

**Comment by sctm002** [comment]
我是用快手做的测试，抖音得略微修改一下代码。一般抖音的博主在快手都有号的，图方便的话，你直接去快手下载就行了。

**Comment by sctm002** [comment]
还有浏览器本身就是不播放视频的，只是做下载用，你点“获取视频源”能正常下载视频就可以了。
